/**
 * Whole-src coverage gate.
 *
 * Runs the unit suite under NODE_V8_COVERAGE, drops V8 entries for node:test's
 * synthetic mock modules (URLs ending in `?node-test-mock=N`), then lets c8
 * report and enforce thresholds from .c8rc.json.
 *
 * Why: `mock.module("./auth")` makes Node evaluate a ~400-byte generated module
 * whose URL is the real file plus a query string and has no source map. c8
 * strips the query and maps those generated byte offsets onto the real source,
 * so it reports lines/branches that do not exist. The real module is measured in
 * the test processes that load it unmocked.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const tmp = path.resolve("coverage/tmp");
fs.rmSync(path.resolve("coverage"), { recursive: true, force: true });
fs.mkdirSync(tmp, { recursive: true });

const bin = (name) => path.resolve("node_modules/.bin", name);
const run = (cmd, args, env = process.env) => {
  const r = spawnSync(cmd, args, { stdio: "inherit", env });
  if (r.status !== 0) process.exit(r.status ?? 1);
};

run(
  process.execPath,
  [
    "--experimental-test-module-mocks",
    "--import",
    "tsx",
    "--import",
    "./src/test/setup.mjs",
    "--test",
    "src/**/*.test.ts",
  ],
  { ...process.env, NODE_V8_COVERAGE: tmp },
);

let dropped = 0;
for (const file of fs.readdirSync(tmp)) {
  const full = path.join(tmp, file);
  const data = JSON.parse(fs.readFileSync(full, "utf8"));
  const before = data.result.length;
  data.result = data.result.filter((r) => !r.url.includes("?node-test-mock="));
  dropped += before - data.result.length;
  fs.writeFileSync(full, JSON.stringify(data));
}
console.log(`coverage: dropped ${dropped} synthetic node:test mock module entries`);

run(bin("c8"), ["report"]);
run(bin("c8"), ["check-coverage"]);
